execution:
    -
        concurrency: 20
        steps: 0
        locations:
            us-east-1: 20
        locationsPercents:
            us-east-1: 100
        executor: jmeter
        scenario: default-scenario-6382363
        hold-for: 2m
        ramp-up: 3m
services:
    -
        module: s3downloader
        aws-params: { region: us-east-1, bucket-name: blazemeter, data-path: users/407077/tests/6382363/reports/r-v4-5bd2c7a97dbb0/data, key-id: ASIA27ZZ6HCK6JG2MBPV, secret: Bb86o1Yiyt2AQhQ5x5sqT+l6ggAsZwCjLs1LehU7, token: FQoGZXIvYXdzECkaDJZE/ZBvS0OTe8iIfyLjA8wI/DVWKZs2xsByYjdUa1fu96bG6PMLweOyGVDVQMKyPZjvPBdhPa4j9k9xvjYGWfqZF82RlYS6thy+dXkFC38fI5x161wtxf4WfNswxs5fsl68tr35JkwBZqn7ETaJ+Ag3xoLaxLC4NozwcHBeksFg3DrlvkA475KMOxJ+ue/GdEW1vgk1FK35bIX25VMFAZiik3rhRmzxacxnu57Vk46Q5whcJav7PjQIPP009zJQi9oqvNUhtg4WOofUt2G2TpDDG9JboRHWr7Cblz1oWq1PM7s9ax+koyGgRRXQ+dMnwHU+D59LYx7cldzGnJE2eyqN3MCMvFD6453rZiiAq7uJjrJzbsDg9y+c0HhYHVhuxkKWa3hQ+0ozEJIeoj2RHzt/XIC5I69n0ndI8PnizrZ/sY8h0WtdJQAqxl4ixst9FNdHv8Kg5MLWoS5BSFJRb7e/77KzwtgeKVgMFKBofAIzdi4WLdLUy0JTIPDF+0KRtwiuVY+m0ZO0wNoFh6r5KeP7wQevEXPXqeAhNLZKsvz9lCxDaZqv/F4ILpA0XVj6Ig87pn7idPXxF6kpCcrhN3i/j95T6CZB9p48CY16Jivsu8KQqMT0wS5vGlbVg/qfqW0+KFk0NdYJ03KA9NOQrOcXmyjZj8veBQ==, url: 's3://blazemeter/users/407077/tests/6382363/reports/r-v4-5bd2c7a97dbb0/' }
scenarios:
    default-scenario-6382363:
        script: NOP_SC2.jmx
        force-parent-sample: false
settings:
    env:
        TAURUS_EXECUTIONS_TOTAL: 1
        TAURUS_EXECUTIONS_INDEX: 1
        TAURUS_SESSIONS_TOTAL: 1
        TAURUS_SESSIONS_INDEX: 1
        TAURUS_LOCATIONS_TOTAL: 1
        TAURUS_LOCATIONS_INDEX: 1
modules:
    jmeter:
        version: auto
    cloud-utils:
        session:
            signature: ci12NC01YmQyYzdhOTdkYmIwOjE1NDE3NDk5Nzc6YTc3ZmJmZDg5ZjMxOGEwZGIzYmE2MzgyODQ2NTljMDEzNmE2NmE5MGFmYWQ3YjU4MzY0NDA4ZDVlNjYyYTkxMWI4NDk3N2Q5NzNiMjEwNjIwYWNlM2U1Y2ZiYWZkMDQyNjE2NTgzY2FlNmQwOTRiMTNkZTA2YzVjYjgzMzY1ZTQ=
            session_id: r-v4-5bd2c7a97dbb0
            master_id: !!float 18438524
            user_id: 407077
            test_id: 6382363
            session_token: ci12NC01YmQyYzdhOTdkYmIwOjE1NDE3NDk5Nzc6YTc3ZmJmZDg5ZjMxOGEwZGIzYmE2MzgyODQ2NTljMDEzNmE2NmE5MGFmYWQ3YjU4MzY0NDA4ZDVlNjYyYTkxMWI4NDk3N2Q5NzNiMjEwNjIwYWNlM2U1Y2ZiYWZkMDQyNjE2NTgzY2FlNmQwOTRiMTNkZTA2YzVjYjgzMzY1ZTQ=
        jetlag-url: 'https://data.blazemeter.com/submit.php?signature={signature}&session_id={session_id}&user_id={user_id}&test_id={test_id}'
        jetlag-download: 'https://s3.amazonaws.com/blazemeter-jetlag/snapshots/jetlag-1.6.6-2018-08-12-14-47-jar-with-dependencies.jar'
        jetlag-args: '-max_labels 100'
        aws-params: { region: us-east-1, bucket-name: blazemeter, data-path: users/407077/tests/6382363/reports/r-v4-5bd2c7a97dbb0/data, key-id: ASIA27ZZ6HCK6JG2MBPV, secret: Bb86o1Yiyt2AQhQ5x5sqT+l6ggAsZwCjLs1LehU7, token: FQoGZXIvYXdzECkaDJZE/ZBvS0OTe8iIfyLjA8wI/DVWKZs2xsByYjdUa1fu96bG6PMLweOyGVDVQMKyPZjvPBdhPa4j9k9xvjYGWfqZF82RlYS6thy+dXkFC38fI5x161wtxf4WfNswxs5fsl68tr35JkwBZqn7ETaJ+Ag3xoLaxLC4NozwcHBeksFg3DrlvkA475KMOxJ+ue/GdEW1vgk1FK35bIX25VMFAZiik3rhRmzxacxnu57Vk46Q5whcJav7PjQIPP009zJQi9oqvNUhtg4WOofUt2G2TpDDG9JboRHWr7Cblz1oWq1PM7s9ax+koyGgRRXQ+dMnwHU+D59LYx7cldzGnJE2eyqN3MCMvFD6453rZiiAq7uJjrJzbsDg9y+c0HhYHVhuxkKWa3hQ+0ozEJIeoj2RHzt/XIC5I69n0ndI8PnizrZ/sY8h0WtdJQAqxl4ixst9FNdHv8Kg5MLWoS5BSFJRb7e/77KzwtgeKVgMFKBofAIzdi4WLdLUy0JTIPDF+0KRtwiuVY+m0ZO0wNoFh6r5KeP7wQevEXPXqeAhNLZKsvz9lCxDaZqv/F4ILpA0XVj6Ig87pn7idPXxF6kpCcrhN3i/j95T6CZB9p48CY16Jivsu8KQqMT0wS5vGlbVg/qfqW0+KFk0NdYJ03KA9NOQrOcXmyjZj8veBQ==, url: 's3://blazemeter/users/407077/tests/6382363/reports/r-v4-5bd2c7a97dbb0/' }
        start-allow-limit: 1ms
        start-limit-exceeded-shutdown: false
        delayed-start: false
        sleep-after: 0
        status-notify-url: 'https://a.blazemeter.com/api/v4/taurus/r-v4-5bd2c7a97dbb0/notify'
        session-token: ci12NC01YmQyYzdhOTdkYmIwOjE1NDE3NDk5Nzc6YTc3ZmJmZDg5ZjMxOGEwZGIzYmE2MzgyODQ2NTljMDEzNmE2NmE5MGFmYWQ3YjU4MzY0NDA4ZDVlNjYyYTkxMWI4NDk3N2Q5NzNiMjEwNjIwYWNlM2U1Y2ZiYWZkMDQyNjE2NTgzY2FlNmQwOTRiMTNkZTA2YzVjYjgzMzY1ZTQ=
        commands-channel:
            url: 'https://a.blazemeter.com/api/v4/taurus/{session_id}/poll'
    blazemeter:
        address: 'https://a.blazemeter.com'
        data-address: 'https://data.blazemeter.com'
    periodic-uploader:
        enabled: true
        upload_interval: 60
    version-switch:
        switch-java: '8'
    passfail:
        class: bzt.engine.Reporter
reporting:
    -
        module: blazemeter
        session-id: r-v4-5bd2c7a97dbb0
        signature: ci12NC01YmQyYzdhOTdkYmIwOjE1NDE3NDk5Nzc6YTc3ZmJmZDg5ZjMxOGEwZGIzYmE2MzgyODQ2NTljMDEzNmE2NmE5MGFmYWQ3YjU4MzY0NDA4ZDVlNjYyYTkxMWI4NDk3N2Q5NzNiMjEwNjIwYWNlM2U1Y2ZiYWZkMDQyNjE2NTgzY2FlNmQwOTRiMTNkZTA2YzVjYjgzMzY1ZTQ=
        send-data: false
        upload-artifacts: false
        test-id: 6382363
        user-id: 407077
